AllCops:
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Rails:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_first_parameter

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
